name: 'AutoUpdate'
 
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: 'Run autoupdate.sh'
      run: bash .github/workflows/autoupdate.sh
    - name: Commit files
      run: |
        git config --local user.email "github-actions@noreply.github.com"
        git config --local user.name "github-actions"
        git add .
        git commit -m "Update `date`" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    - name: Mirror Github to Gitee with white list
      uses: Yikun/hub-mirror-action@master 
      with:
        src: github/kkzzhizhou 
        dst: gitee/kkzzhizhou
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        static_list: 'scoop-apps'
        force_update: true

